- name: Role checks
  ansible.builtin.include_tasks: preflight.yaml

- name: Install CoreDNS
  ansible.builtin.include_tasks: "{{ coredns_install_method }}.install.yaml"

- name: Verify CoreDNS is working
  ansible.builtin.include_tasks: verify.yaml

- name: Post install
  ansible.builtin.include_tasks: post-install.yaml
