- name: Get CoreDNS service status
  ansible.builtin.systemd_service:
    name: coredns
  register: coredns_service

- name: Assert CoreDNS service is active
  ansible.builtin.assert:
    that:
      # TODO: curl health endpoint (localhost:{{ coredns_healthcheck_port }}/health) - returns `OK`
      # TODO: do a dns lookup
      - "coredns_service.status.ActiveState == 'active'"
    success_msg: "CoreDNS is successfully installed and is running"
    fail_msg: "The service: {{ coredns_service.name }} is not running!"
  when: coredns_service is defined
